### ISSUE TITLE
Rest Api and maps/keywords

### ISSUE THREAD

**Issue by hirthjo** [tomhanika/conexp-clj#101]
In conexp.api.handler the read-data function does only evaluate the keys of a map. Values are untouched. 
For write-fca we need to evaluate v to the content of a variable.

 ```
"map" (if (some? raw)
                (into {} (for [[k v] raw] [(edn/read-string (name k)) v])))
```

For other I/O methods, we need the API option to convert inputs to keywords.

**Comment by jana-fischer** [comment]
The issue was fixed in the linked PR.
