### ISSUE TITLE
Rediscover Titanic in History

### ISSUE THREAD

**Issue by De-Narm** [tomhanika/conexp-clj#36]
(...and maybe change drawing accordingly.)

**Comment by hirthjo** [comment]
Using the `titanic-iceberg-intent-seq` throws an IllegalArgumentException for some percentage thresholds and data sets, e.g. mushroom 5%.
_Comparison method violates its general contract!_

**Comment by De-Narm** [comment]
Error should be fixed (<= should have been <). While trivial, the error surprisingly never came up before.

**Comment by tomhanika** [comment]
#53
