### ISSUE TITLE
Disable Wiki

### ISSUE THREAD

**Issue by exot** [tomhanika/conexp-clj#50]
The wiki has been superseded by the documentation contained directly in the code repository of conexp-clj.  I would propose to either disable it completely, or remove all files but the main Home.md file, containing only a line akin to

    This wiki is obsolete, please refere to the [official documentation](https://github.com/tomhanika/conexp-clj/README.md) of `conexp-clj`.

**Comment by tomhanika** [comment]
Resolved :)
